# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
enable-beta-ecosystems: true
updates: 
  - package-ecosystem: uv
    directory: /api/
    schedule:
      interval: weekly
      day: friday

  - package-ecosystem: npm
    directory: /web/
    schedule:
      interval: weekly
      day: friday

  - package-ecosystem: docker
    directories:
      - /web/
      - /api/
    schedule:
      interval: weekly
      day: friday
  
  - package-ecosystem: docker-compose
    directory: /
    schedule:
      interval: weekly
