api:
  - changed-files:
      - all-globs-to-any-file:
          - "api/**"
          - "!api/Dockerfile"

ci:
  - changed-files:
      - all-globs-to-any-file:
          - ".github/**"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - "compose.yaml"

web:
  - changed-files:
      - all-globs-to-any-file:
          - "web/**"
          - "!web/Dockerfile"
