api:
  - changed-files:
      - all-globs-to-any-file:
          - "api/**"
          - "!api/Dockerfile"

docker:
  - changed-files:
      - any-glob-to-any-file:
          - "**/Dockerfile"
          - "compose.yaml"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - "**/uv.lock"
          - "**/package-lock.json"

github:
  - changed-files:
      - all-globs-to-any-file:
          - ".github/**"

web:
  - changed-files:
      - all-globs-to-any-file:
          - "web/**"
          - "!web/Dockerfile"
