name: chipmunks

services:
  proxy:
    image: docker.io/traefik:v3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
    restart: always
    command: --api.insecure=true --providers.docker
    volumes:
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
    ports:
      - "8080:80"
      - "8081:8080"
    depends_on:
      - web
      - api

  api:
    build:
      context: ./api/
      target: dev
    labels:
      - traefik.http.routers.web.rule=Path(`/api/v1`)
    develop:
      watch:
        - action: sync
          path: ./api/app/
          target: /app/app/
        - action: rebuild
          path: ./api/pyproject.toml
        - action: rebuild
          path: ./api/uv.lock

  web:
    build:
      context: ./web/
      target: dev
    labels:
      - traefik.http.routers.web.rule=Path(`/`)
    environment:
      - __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS=web
    develop:
      watch:
        - action: sync
          path: ./web/src/
          target: /app/src/
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/package-lock.json
  