name: chipmunks

services:
  proxy:
    image: docker.io/traefik:v3.3.4@sha256:cc11989f418e2cfe5e60fc40c92c1813be847f58eda15eced7d5ac890255ad9e
    restart: always
    command:
      - --api.insecure=true
      - --providers.docker
      - --providers.docker.exposedbydefault=false
    volumes:
      # Podman users: set DOCKER_SOCK to Podman socket location
      - ${DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock:ro
    ports:
      - "8000:80"
      - "8080:8080"
    depends_on:
      - web
      - api
    privileged: true # Needed for rootless Podman

  api:
    build:
      context: ./api/
      # Set CHIPMUNKS_TARGET or CHIPMUNKS_API_TARGET to prod for production
      # build or dev (default) for hot reloading
      target: ${CHIPMUNKS_API_TARGET:-${CHIPMUNKS_TARGET:-dev}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=PathPrefix(`/api/v1`)
    develop:
      watch:
        - action: sync+restart
          path: ./api/app/
          target: /app/app/
        - action: sync+restart
          path: ./api/settings.${CHIPMUNKS_API_TARGET:-${CHIPMUNKS_TARGET:-dev}}.toml
          target: /app/settings.toml
        - action: rebuild
          path: ./api/pyproject.toml
        - action: rebuild
          path: ./api/uv.lock

  web:
    build:
      context: ./web/
      # Set CHIPMUNKS_TARGET or CHIPMUNKS_WEB_TARGET to prod for production
      # build or dev (default) for hot reloading
      target: ${CHIPMUNKS_WEB_TARGET:-${CHIPMUNKS_TARGET:-dev}}
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=PathPrefix(`/`)
    develop:
      watch:
        - action: sync
          path: ./web/
          target: /app/
        - action: rebuild
          path: ./web/package.json
        - action: rebuild
          path: ./web/package-lock.json
