# SPDX-FileCopyrightText: © 2025 Molly Rose <molly@mollymorphous.dev>
# SPDX-License-Identifier: AGPL-3.0-or-later

[formatting]
array_auto_collapse = false
indent_string = "    "

[[rule]]
include = ["**/pyproject.toml"]
keys = ["project"]

[rule.formatting]
reorder_arrays = true
