# Continuous Integration for the Web module

name: "Web"

on:
  push:
    branches: [main]
    paths: ["api/**", ".github/workflows/web.yml"]
  pull_request:
    branches: [main]
    paths: ["api/**", ".github/workflows/web.yml"]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./web/package-lock.json
          node-version-file: ./web/.node-version
      - name: Install dependencies
        working-directory: ./web/
        run: npm ci
      - name: Set up Next.js cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-${{ runner.arch }}-nextjs-${{ hashFiles('web/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-nextjs-${{ hashFiles('web/package-lock.json') }}-
      - name: Run Next.js build
        working-directory: ./web/
        run: npm run build

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: ./web/package-lock.json
          node-version-file: ./web/.node-version
      - name: Install dependencies
        working-directory: ./web/
        run: npm ci
      - name: Run Prettier
        working-directory: ./web/
        run: npx prettier -c .
